services:
  web:
    image: protoseo/gundog-api:v0.0.1
    container_name: gundog-api
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_URL: jdbc:mysql://db:3306/gundog?rewriteBatchedStatements=true
      DB_USER: user
      DB_PASSWORD: mypass
    depends_on:
      - db
    networks:
      - gundog-network
  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gundog
      MARIADB_USER: user
      MARIADB_PASSWORD: mypass
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--default-time-zone=+09:00"]
    networks:
      - gundog-network
networks:
  gundog-network:
