name: ci

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'feature/deploy'

jobs:
#   image-build:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v3
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: protoseo/gundog-api:v0.0.1
  deploy-aws:
#     needs: image-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Run Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: echo "hello"
